apiVersion: v1
kind: Secret
metadata:
  namespace: feedservice
  name: postgres-secret
  labels:
    app: feedservice
    env: dev
type: Opaque
data:
  POSTGRES_DB: bXlkYg==           # mydb
  POSTGRES_USER: bXl1c2Vy         # myuser
  POSTGRES_PASSWORD: bXlwYXNzd29yZA==  # mypassword
